### ISSUE TITLE
Announcer: gun suggestions

### ISSUE THREAD

**Issue by itVictor** [redsunservers/VSH-Rewrite#102]
1. add better sound on successful hit (current one isn't that noticeable/loud enough)
2. add some kind of visual indicator on successful hit; could do damage numbers by making it deal only 1 damage, or show text to screen on hit ("player will join your team in x seconds!")
3. make gun more useful when hitting sentries/buildings in general, currently only does 40 damage like normal revolvers, could potentially make it instakill like legacy vsh

**Comment by FortyTwoFortyTwo** [comment]
Another idea for buildings: swap its team on shot. Similar to Vagineer's old rage reverse control for buildings, but should be less spammy.
