### ISSUE TITLE
Weapon Reskin Decloning Proposition

### ISSUE THREAD

**Issue by Waifers** [redsunservers/VSH-Rewrite#105]
There's plenty is gimmicky stuff that could be done and with the amount of reskins there are, they could be used to provide a handful of different options, ranging from having slight differences to pretty much being a new weapon without having to cannibalize an existing weapon in the process.

These are the list of accessible (aka craftable) reskins that could plausibly receive new stats to differentiate from their original counterpart.

- Three-Runed Blade
- Unarmed Combat
- Nostromo Napalmer
- Maul
- Postal Pummeler
- Lollichop
- Bootlegger
- Nessie's Nine Iron
- Scottish Handshake
- Apoco-Fists
- AWPer Hand
- Fortified Compound
- Wanga Prick
- Sharp Dresser
- Conscientious Objector
- Freedom Staff
- Bat Outta Hell
- Ham Shank

An rough example of how one of these weapons could be changed is below.

**Nessie's Nine Iron**
- +Movespeed bonus per head
- -No damage bonus per head
- -25 Max Health (attribute 125)
- -No crit boost (attribute 288)

Expanding the options players have, in my opinion, is something that is worth doing while it also helps keep the mode fresh with new stuff for the Red team to play with.

**Comment by FortyTwoFortyTwo** [comment]
As much as i want TF2 have more weapons to play around with different balances, i still wouldn't want to modify any reskins and bring confusions as it different to original weapons.
There is still many TF2 weapons that have a use, but still barely used much (even modified from VSH). Those can be changed to similar or something completely new.
I would modify those weapons first before anywhere considering into doing reskins
