### ISSUE TITLE
Uber Ranger Concept (Slag FF2 Boss)

### ISSUE THREAD

**Issue by Waifers** [redsunservers/VSH-Rewrite#24]
Here is your medic boss, straight from slag ff2. Unfortunately, I can't read or write code for shit nor do I have any access to the code for slag ff2 so only ideas here for now.

Origin: https://www.youtube.com/watch?v=q_TP32PujpM

Slag FF2: Uber Ranger went through two iterations during slag ff2, I will dub them "Uber Rangers" and "White Uber Ranger". 

1. The "Uber Rangers": A boss where **six** players played as the Uber Rangers, each with a super jump and a self uber rage. Each player also had different starting health based on their place in the queue, with the person first in queue having the highest health while the person that was sixth in queue had the lowest. This shit got removed in favor of the White Uber Ranger, partially because of queue points shit and how having six semi competent people playing them would absolutely annihilate everything.

2. White Uber Ranger: A hybrid between a solo boss and the original Uber Rangers boss. ~~Here my memory of the second iteration is too hazy so I doubt this is going to be completely accurate.~~ The White Uber Ranger is pretty much the Uber Rangers as one boss, but now his rage also summoned a weaker Uber Ranger minion as a miniboss.

Theme and Models from Slag (Shits been dead lmao): https://www.dropbox.com/sh/2abrv34vy6cl8jo/AAAe11wfLUf0EjQGkpqlaKMda?dl=0

With those out of the way, here is how an Uber Ranger would probably be in rewrite, vanity and all.

- Round Start Sound: Medic_battlecry05.wav

- Theme: uber_theme.mp3

- Model: uberranger_white.mdl

- Melee: Ubersaw with the same damage as most other boss melees, but with the ubersaw slower firing rate kept.

- Weaker than average super jump.

- Below average health (Painis level possibly) and average rage damage requirement.

- 100% Rage: 6 Second AoE Invulnerability Uber + One Uber Ranger miniboss summoned based on one of the current top 3 dead contributors from Red team.

- 200% Rage: 8 Second AoE Invulnerability Uber + Three Uber Ranger minibosses summoned based on the current top 3 dead contributors from Red team.

- Uber Ranger minibosses: Tankier than the Seeldier minions with their damage output. Spawns with an Ubersaw and Medigun that can be used like any other Medigun (with gimped healing rate if any).

- Each Uber Ranger summon has slight diminishing returns, with them having a base health that decreases with each additional summon (Uber Ranger summon order would be Red -> Blue -> Green -> Yellow -> Pink -> Black). Once an Uber Ranger dies, they can't be re-summoned.

Rough draft, but if this idea is compelling enough, than it can be polished with balancing in mind and with coding as well.

**Comment by FortyTwoFortyTwo** [comment]
This is probably the best medic boss we can go for VSH-Rewrite, i didn't know there a second version of uber rangers, and i do very much prefer the latter.

I'm unsure about having weaker super jump if were also having lowest health and ubersaw slower firing rate, lowest health should definitely stay.

Uber ranger could heal eachother normally, but not when building health/uber percent to main boss when some dumb idiot would hide at corner of map to rebuild health/uber. Dunno if normal uber pop would be enough for it, perhaps a different boost could be given to main boss while healing?

Otherwise i'm good with this idea, anyone can work into making this boss.
