### ISSUE TITLE
GRU change

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/VSH-Rewrite#28]
I think the GRU needs a buff. The speed doesnt help against a hale, if he focus you, you are dead and cant do anything, so even as a last resort, it wont really help. Im not sure a second speed buff would be better since gentlespy would have to solo rage him, but something like a climb ability, a small one like (like the sniper) would make it actually more viable. Right now its only usefull against gentlespy

**Comment by UrUgli** [comment]
I mean, it being a "diet eviction" would be the same as saying "tribalman shiv is a diet kukri". It's just there is two different options to play, a fast climb, or one big jump. Same with GRU, the speed here isn't viable enough to help you other than "reposition" yourself and against that's if you aren't dead.

**Comment by FortyTwoFortyTwo** [comment]
I wouldn't think giving extra speed is a good choice. As forged said, another jump height wouldn't make much change. You would rework GRU to something complete new, possibly still somewhat related to speed bonus, but i don't have any ideas right now.
