### ISSUE TITLE
Redmond Mann spells stop working on the Redmond and Blutarch DUO

### ISSUE THREAD

**Issue by Darkita162** [redsunservers/VSH-Rewrite#324]
Not sure if this is an issue with the server acting up today or if this is a new bug. But if Redmond uses his rage ability to summon a ghost Monoculus and it spawns in an area where it cant spawn, such as a tight door way, it seems to disable both spells. Including his teleport spell and his rage ability. Scouts getting scared upon rage activation still functions, however spells no longer function, as the "cannnot interact" sound effect players instead, indicating that a spell isnt selected.

**Comment by FortyTwoFortyTwo** [comment]
Moved to VSH-Rewrite repo. I've known this kind of issue that using mono spells in cramp spot wouldn't work properly. Normally TF2 would've refunded it, but VSH didn't take into account with it
