### ISSUE TITLE
Degreaser rebalance 

### ISSUE THREAD

**Issue by Wes-the-mew** [redsunservers/VSH-Rewrite#334]
Degreaser's stats should be inverted.

The point of the weapon is for pyro to be more agile with its increased switch speed.
So give it a weaker airblast (say 25 or 33% or even 50% weaker) but give it a shorter cool down.

(Idea by Rinzor)

**Comment by FortyTwoFortyTwo** [comment]
This idea would make airblasting even more spammy, which i'm not into making weapons very spammy to use.
