### ISSUE TITLE
Error while trying to compile 1.11

### ISSUE THREAD

**Issue by CRYHACK** [redsunservers/VSH-Rewrite#374]
Getting this error message:

vsh\bosses\boss_announcer.sp(441) : error 092: number of arguments does not match definition

**Comment by FortyTwoFortyTwo** [comment]
[From the line causing error.](https://github.com/redsunservers/VSH-Rewrite/blob/422fb38483b9f53ffae7f28ab2f5cf34b0ee3bdc/addons/sourcemod/scripting/vsh/bosses/boss_announcer.sp#L441)

Seems like you're using outdated version of `tf2attributes.inc` include, you'll need to update both include and plugin for `TF2Attrib_ListDefIndices`'s 3rd param on max attribs.
You can find latest version [here](https://github.com/FlaminSarge/tf2attributes/blob/master/tf2attributes.inc).

**Comment by CRYHACK** [comment]
Thanks alot worked :)
