### ISSUE TITLE
balloonicorn pyro boss 

### ISSUE THREAD

**Issue by forgedisaman** [redsunservers/VSH-Rewrite#58]
base class - pyro

cosmetics - combustible cutie, balloonihoodie, balloonicorn, scorched skirt, crispy golden locks.

boss theme - Do you believe in magic (by the lovin spoonful)

https://www.youtube.com/watch?v=ATY3-8PlCRw < link there if you haven't heard it.

hp - 700 per player

recharge ability - jetpack

melee weapon - lolichop (face melting)

deals around 165 damage per hit

gains rage after taking 3000 damage

rage - grants the pyro an aoe effect (based on the taunt kill of the rainblower)
the rage would set targets on fire that stay in the area and deals afterburn damage.
the aoe area extends out in a small sphere around the pyro (don't really have a set hammer unit size for it, between 600 and 800 sounds like a good range)
it will fade away after 8 seconds of being active.

anyone killed by this becomes a balloonicorn minion with the ability of a jetpack. (using a balloonicorn model on top of a small pyro with a jetpack and fire axe)
the minions don't do a lot of damage, somewhere between 30 and 40 in my opinion sounds fair.

boss passive: everybody on the server visits pyro land :) (applies the pyrovision goggles effect to everyone on the server)

thoughts and feedback would be appreciated, especially if someone could help me out with the ranges for the rage being acquired and the rage radius. (that would be great)

**Comment by Mikusch** [comment]
I'm not the project maintainer but I don't think that a Pyro with cosmetics would make for a good iconic boss. The way you wrote this up is that you want the Ballonicorn to be a simple minion when it should really be the main boss and spawn the babies from Meet the Pyro as minions instead.
With that all said, I have nothing against the initial idea of a Ballonicorn boss but not the way it is described here.
But of course @FortyTwoFortyTwo has the last say in this.

**Comment by FortyTwoFortyTwo** [comment]
I agree with @Mikusch on the cosmetics. I'm more thinking of a "classic" style of boss, not take 2 semi-new elite grade (does that also breaks econ violation?), also scorched skirt and crispy golden locks doesn't really fit much to it.
Item set from Pyromania update (Burning Bongos, Infernal Orchestrina and Balloonicorn) would fit better to it, but all 3 is somewhat small to see much difference ~~though we have demopan and painis cupcakes~~.

I'm half into the jetpack idea. It can be a nice passive ability, but sounds like a shiitter version of brave jump, and does it really fit much to Balloonicorn?

165 damage is not really needed for this, just go normal 182 damage.

Whole rage idea sounds fine, obviously will need number changes after playtests. Though the minion sounds very little to none, needing to be killed from said rage while only dealing 35 damage. Compare that to seeldier or announcer minions.

Also i'm hoping to see Rainblower used somewhere. How will it work? Don't have anything specific from me to use Rainblower.

**Comment by forgedisaman** [comment]
this is very much experimental rn so the cosmetics might be hit or miss, I could go completely off the rails and use an upscaled balloonicorn model instead of an actual pyro model (depending on if I can figure out scaling or not) as for minions having lower damage that was because of their jetpack ability and them having much more mobility than the seeman minions. as for the rainblower I was thinking about converting the airblast knockback into a negative to pull people closer to the boss (making it easier to group people up and pull them into your rage) the damage on the actual flames would have to be nerfed if it was included.

**Comment by UrUgli** [comment]
I do believe the balloonicorn boss model is already a thing. I remember fighting one back in 2014.

**Comment by FortyTwoFortyTwo** [comment]
Decided to not add this, not really based off something or part of classic/original boss. VSH-Rewrite should only have 1, decent pyro boss that fits well to it.
