### ISSUE TITLE
Tohru-Friendly "Totally Not Sans" Boss

### ISSUE THREAD

**Issue by Waifers** [redsunservers/VSH-Rewrite#92]
https://github.com/redsunservers/VSH-Rewrite/pull/91#pullrequestreview-332232112

Sans is now a spy with these cosmetics
Breakneck Baggies
Dead Head
Puffy Provocateur

it fits within the vsh guidelines now you cant stop this

**Comment by EgocentricPoliceDick** [comment]
cancer is still cancer no matter how it's dressed up
