### ISSUE TITLE
Team Dome

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/VSH-Rewrite#99]
Lots of ideas by Zane so thanks for that.

Currently dome deals damage to both team, pushing both to near death. However usually only one team need to be in penalty from dome, depending on which team stalls. So this Team Dome idea popped up for this.

- Dome does not appear/start automatically, But CP unlocks instead. likely using same timer as current dome.
- Capture time should not be based from map's time, always same/hard set from plugin.
- Both team can capture. Team cannot block capture progress, but capture rate will be slowed down instead.
- Once CP is captured, round won't end but dome will spawn instead. Dome color will be same as whoever team captured point.
- Dome will only deal damage to whoever team not owner of CP capped.
- Team can recapture CP to flip dome color and damage to opposite team.
- Dome speed will likely be faster to compensate with cap required to start dome.
- Dome freeze depends on who captured CP. If attack team, freeze when attack team died. If boss team, freeze when attack team damages boss. This idea is for losing team to counter back captured team, showing less stall happening.
- Somehow deal with map's new dome pos from config, possibly X radius needing to be nearby CP to capture.

**Comment by Zane-Truesdale** [comment]
Two more ideas I thought of while pacing around my kitchen for 25 minutes.

1. **CP timer unaffected by freezes.** There are a lot of games where the dome does not trigger until the last few players (in most cases, the stallers) are the ones left alive. Point unlocking sooner without pausing would help speed things up.

2. **Hale gets scaling capture rate increase based on player count.** What attack team lacks in raw power is made up for in quantity, and that's what matters most in capping a control point. If capture rate is gonna be longer, then hale could benefit from getting a +1 to capture rate for every 2 or 3 players on red team. Considering that ~20 players is pretty much the average in active server VSH rounds, it shouldn't be too big of a bonus to hale
